### ISSUE TITLE
Does not build on iOS

### ISSUE THREAD

**Issue by Z6P0** [romikavinda/app_integrity_checker#1]
```
Failed to build iOS app
Swift Compiler Error (Xcode): Type 'IOSSecuritySuite' has no member 'getMachOFileHashValue'
/Users/patrick/.pub-cache/hosted/pub.dev/app_integrity_checker-1.0.2/ios/Classes/AppIntegrityCheckerPlugin.swift:18:49

Swift Compiler Error (Xcode): Cannot infer contextual base in reference to member 'default'
/Users/patrick/.pub-cache/hosted/pub.dev/app_integrity_checker-1.0.2/ios/Classes/AppIntegrityCheckerPlugin.swift:18:72

Swift Compiler Error (Xcode): Type 'IOSSecuritySuite' has no member 'getMachOFileHashValue'
/Users/patrick/.pub-cache/hosted/pub.dev/app_integrity_checker-1.0.2/ios/Classes/AppIntegrityCheckerPlugin.swift:19:50

Swift Compiler Error (Xcode): Cannot infer contextual base in reference to member 'custom'
/Users/patrick/.pub-cache/hosted/pub.dev/app_integrity_checker-1.0.2/ios/Classes/AppIntegrityCheckerPlugin.swift:19:73

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro.
```

**Comment by romikavinda** [comment]
Please run pod install since this plugin depends on  [IOSSecuritySuite pod](https://github.com/securing/IOSSecuritySuite)

**Comment by Z6P0** [comment]
I added the line `pod 'IOSSecuritySuite'` in ios/Podfile and then run `pod install` but still the same error...
N.B. I'm not familiar with iOS development. Did I miss something?

**Comment by romikavinda** [comment]
try running Flutter run --release which will take care of all the dependencies , afterwards try building app on Xcode IDE

**Comment by Z6P0** [comment]
Error:
`Release mode is not supported by iPhone 14 Pro.`
Is it because I don't have a real device?
How to build and test the app on simulator?

**Comment by romikavinda** [comment]
Try running flutter run -v which will build the app in debug mode

**Comment by Z6P0** [comment]
Same error:

```
[        ] Swift Compiler Error (Xcode): Type 'IOSSecuritySuite' has no member 'getMachOFileHashValue'
           /Users/patrick/.pub-cache/hosted/pub.dev/app_integrity_checker-1.0.2/ios/Classes/AppIntegrityCheckerPlugin.swift:18:49
           
[        ] Swift Compiler Error (Xcode): Cannot infer contextual base in reference to member 'default'
           /Users/patrick/.pub-cache/hosted/pub.dev/app_integrity_checker-1.0.2/ios/Classes/AppIntegrityCheckerPlugin.swift:18:72
           
[        ] Swift Compiler Error (Xcode): Type 'IOSSecuritySuite' has no member 'getMachOFileHashValue'
           /Users/patrick/.pub-cache/hosted/pub.dev/app_integrity_checker-1.0.2/ios/Classes/AppIntegrityCheckerPlugin.swift:19:50
           
[        ] Swift Compiler Error (Xcode): Cannot infer contextual base in reference to member 'custom'
           /Users/patrick/.pub-cache/hosted/pub.dev/app_integrity_checker-1.0.2/ios/Classes/AppIntegrityCheckerPlugin.swift:19:73
           
[        ] Could not build the application for the simulator.
[        ] Error launching application on iPhone 14 Pro.
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:790:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1367:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:348:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:294:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:112:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
```

**Comment by romikavinda** [comment]
I looked into this issue and following is the cause,

For iOS , the module IOSSecuritySuite is used to check the file integrity and some of the methods used in this module are only available for arm64 architecture (Build target).

`private static func checkMachO(_ imageName: String, with expectedSha256Value: String) -> Bool {
 #if arch(arm64)
        if let hashValue = getMachOFileHashValue(.custom(imageName)), hashValue != expectedSha256Value {
            return true
        }
 #endif
        return false
    }
    
}`

Therefore if the build target is not arm64 , in your case which is the emulator , the compiler will throw an error indicating the following methods are not implemented. This works on a real physical device which is what I used while coding this plugin.

As a solution you can either change the build target to arm64 device or declare this plugin as a dependency override [FlutterDocs](https://dart.dev/tools/pub/dependencies#dependency-overrides) for your project and comment out the 2 methods that uses the IOSSEcuritySuite in AppIntegrityCheckerPlugin.swift file for getCheckSum method and use the plugin. 

`let hashValue = IOSSecuritySuite.getMachOFileHashValue(.default)
let hashValue2 = IOSSecuritySuite.getMachOFileHashValue(.custom("IOSSecuritySuite"))
let finvalue = hashvalue3.prefix(8)`



This will return the checksum of dart code only.

**Comment by Z6P0** [comment]
Thanks! I'm not sure I want to buy an iPhone only for this, so I'll try to find another solution...

**Comment by romikavinda** [comment]
I have updated the plugin version to 1.0.3 and made the methods in question work only on arm64. So the compiler will not throw any errors for emulators. The 24 character string will be given for physical devices and for emulators 8 character string of dart code checksum will returned.
