### ISSUE TITLE
Functionality of the dependency

### ISSUE THREAD

**Issue by franciscogodoy97** [romikavinda/app_integrity_checker#3]
I didn't quite understand how this dependency works, how do you validate that the signature and the code are correct?

**Comment by romikavinda** [comment]
This is a library to get the package signature and code checksum of an app, which is a unique value for each release/version of the app you build. Validation is done at runtime by matching the values. If the code or the package has been tampered by a 3rd party the values given by the library will differ from the values you got initially when you released the app. Which helps you to identify whether the app has been modified by an external party and block/limit functionality of the app.
